name: Build and Release

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Build the solution
      run: dotnet build -c Release

    - name: Zip output
      run: Compress-Archive -Path ./bin/Release -DestinationPath JonTestConsole.zip
 
    - name: Create a release and upload asset
      id: create-release-and-upload
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./JonTestConsole.zip
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
  