name: Build and Release

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Build the solution
      run: dotnet build -c Release

    - name: Zip output
      run: Compress-Archive -Path ./bin/Release -DestinationPath JonTestConsole.zip

    - name: Upload to releases
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./JonTestConsole.zip
        asset_name: JonTestConsole.zip
        asset_content_type: application/zip

  create-release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Get latest release
      id: get-latest-release
      run: echo "::set-output name=version::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' | cut -c 2-)"

    - name: Increment version
      id: increment-version
      run: echo "::set-output name=version::$((${{ steps.get-latest-release.outputs.version }} + 1))"
  
    - name: Create a release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ steps.increment-version.outputs.version }}
        release_name: Release v${{ steps.increment-version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get release ID
      run: echo "::set-output name=release_id::${{ steps.create-release.outputs.id }}"